### ISSUE TITLE
An error was encountered while executing action link

### ISSUE THREAD

**Issue by indiesquidge** [anishathalye/dotbot#8] opened 2014-12-24 00:09 UTC
Here is my current install.conf.yaml file:

``` sh
#!/usr/bin/env bash

- clean: ['~']

set -e

- link:
  ~/.tmux.conf: tmux.conf
  ~/.vim: vim/
  ~/.vimrc: vimrc
  ~/.zsh: zsh/
  ~/.zshrc: zshrc

- shell:
  - [git submodule update --init --recursive, Installing/updating submodules]
```

Here is my install script:

``` zsh
#!/usr/bin/env bash

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
```

Here is my output:

``` zsh
All targets have been cleaned
An error was encountered while executing action link
Action link not handled
Action ~/.zsh not handled
Action ~/.vimrc not handled
Action ~/.vim not handled
Action ~/.zshrc not handled
Action ~/.tmux.conf not handled
Installing/updating submodules [git submodule update --init --recursive]
All commands have been executed

==> Some tasks were not executed successfully
```

This happens no matter what. I have created and destroyed multiple vimrc, zshrc, etc. files, I have completely removed Dotbot and re-downloaded it, I have tried using JSON formatting. Nothing I seem to try will let me create the links. I'm not sure what the problem is at this point; any suggestions will be appreciated.

**Comment by caiofbpa** [comment] 2015-03-25 16:54
I've just run into this problem too, and I would like to suggest a mention to this 4-space indentation requirement somewhere in the README to make it easier for other people to use dotbot. :)

**Comment by anishathalye** [comment] 2015-03-26 04:57
Do you think it would be enough to add something like this as a fourth paragraph in the [Configuration](https://github.com/anishathalye/dotbot/blob/master/README.md#configuration) section:

>   When writing nested constructs, keep in mind that YAML is whitespace-sensitive. Following the spacing used in the examples is a good idea.

**Comment by caiofbpa** [comment] 2015-03-26 12:38
I'm not sure if that's clear enough. YAML seems to require **at least** 4 spaces of indentation, maybe this specific information should be mentioned.

Another option is to make dotbot show more meaningful error messages. When I tried with two spaces, dotbot's output was:

    Action ~/.gitconfig not handled
    An error was encountered while executing action link
    ==> Some tasks were not executed successfully

This didn't give me any clue about the indentation problem, maybe dotbot could give us more information about what's gone wrong.

**Comment by anishathalye** [comment] 2015-03-26 19:14
YAML doesn't need 4 spaces of indentation, it just needs to be indented more than the `link` (so that it's under link, rather than having an object with multiple properties, with `link` being null. 3 spaces suffices.

This isn't exactly Dotbot-specific -- it's about the YAML format itself.

Showing a more meaningful error message for this would be a little tricky. Maybe a custom parser would be better for this, but if someone writes a config file that's valid YAML but doesn't make sense for Dotbot, it's a little tricky to pinpoint exactly why something went wrong.

**Comment by caiofbpa** [comment] 2015-03-27 02:18
I see, you're right. Hopefully other people will be more acquainted than I was with the YAML syntax. I agree on that paragraph you suggested before, it'll at least call people's attention to whitespaces and indentation. Thanks for the thorough clarifications.

**Comment by anishathalye** [comment] 2015-03-27 02:42
Okay, great. I've added the paragraph in bdc1b2.

**Comment by Soukyuu** [comment] 2017-01-10 18:54
I'm sorry to resurrect this, but what else could cause that error message? I am setting up another machine using files I created a looong time ago for this one and it fails with the same error message. The spaces seem fine, though:
```
- clean: ['~']

- link:
    ~/.bash_profile: bash_profile
    ~/.bashrc: bashrc
    ~/.ssh/config:
        path: ssh/config
        create: true
    ~/.config/deadbeef:
        path: config/deadbeef/
        create: true
```
It processes `bash_profile` and `bash_rc` then dies with "Action link not handled" Did something change between the dotbot versions that made this syntax invalid?

**Comment by anishathalye** [comment] 2017-01-10 19:57
Hmm, the syntax looks valid. Also, your dotfiles are probably locked to a specific version of Dotbot, right? (like if you're using submodules) What version of Dotbot are you using?

**Comment by Soukyuu** [comment] 2017-01-10 20:00
I am not sure, I just pulled the whole git repo from the second PC and ran ./install
The usual `dotbot --version` doesn't seem to print the version, how do I check?

**Comment by anishathalye** [comment] 2017-01-10 20:25
`git submodule status | grep dotbot`

**Comment by Soukyuu** [comment] 2017-01-10 20:28
`dcc3a1947a85aaa038d143f9f6a0c2a1c1a76a15 dotbot (v1.6.0-5-gdc3a19)`, it seems. Should I update?

**Comment by anishathalye** [comment] 2017-01-10 20:29
Maybe try it with the latest version and see if that works?

**Comment by Soukyuu** [comment] 2017-01-10 21:43
Sorry, I have only a vague idea about how submodules work. I managed to update to the latest version now (I think). It parses the script just fine now. 

The confusing part is that I did not modify that file since I've set it up, so I expected it to just work with the old version as well. In any case, it's working now, thanks for the hint about the locked version.

**Comment by anishathalye** [comment] 2017-01-10 22:46
Hmm, there's no reason it shouldn't have worked with the old version… glad you got it working, though!

Let me know if you decide to investigate / figure it out. Closing this issue for now.

**Closed by anishathalye** 2017-01-10 22:46 UTC
Labels: question

**Comment by shawntoffel** [comment] 2017-09-14 21:42
Encountered the same error message running on a windows 10 machine with python 2.7.13 and git shell (MINGW64).

```
$ ./install
All targets have been cleaned
An error was encountered while executing action link
Action link not handled
```

Upon further investigation the root cause of my issue was that git shell didn't have sufficient permissions to create a symlink. Running git shell as admin resolved the issue.

**Comment by arcticicestudio** [comment] 2017-09-15 03:27
Might be related to #137.

**Comment by Bluesboy** [comment] 2017-10-29 01:11
@shawntoffel it worked for me too. Thanks for posting this workaround.

**Comment by PurpleBooth** [comment] 2020-06-18 06:32
It's baaaaack 

I'm indenting with 4 spaces.

```
- defaults:
    link:
        relink: true
        create: true
        force: true
    shell:
        stdin: true
        stdout: true
        stderr: true
    clean:
        force: true

- clean:
    ~/:
        force: true
    ~/.config:
        recursive: true
    ~/.tmux:
        recursive: true
    ~/.gnupg:
        recursive: true
    ~/Documents/Code:
        force: false

- link:
    # Convenience
    ~/Documents/Code: ~/Code
    # Bash
    ~/.bashrc: bash/xdg-shim
    ~/.config/bash/bashrc: bash/bashrc
    # Fasd
    ~/.fasdrc: fasd/.fasdrc
    ~/.config/fasd/.fasdrc: fasd/.fasdrc
    # Fish
    ~/.config/fish/config.fish: fish/config.fish
    ~/.config/fish/fishfile: fish/fishfile
    ~/.config/fish/functions/:
        glob: true
        path: fish/functions/*
    # Git
    ~/.config/git/config: git/config
    ~/.config/git/config.insteadofhttp: git/config.insteadofhttp
    ~/.config/git/message: git/message
    ~/.config/git/ignore: git/ignore
    ~/.config/git/init-template/hooks/prepare-commit-msg:
        path: /usr/local/bin/mit-prepare-commit-msg
        ignore-missing: true
    ~/.config/git/init-template/hooks/commit-msg:
        path: /usr/local/bin/mit-commit-msg
        ignore-missing: true
    ~/.config/git/init-template/hooks/pre-commit:
        path: /usr/local/bin/mit-pre-commit
        ignore-missing: true
    # git-mit
    ~/.config/git-mit/authors.yml: git-mit/authors.yml
    # Git Duet
    ~/.config/git-duet/authors.yml: git-duet/authors.yml
    ~/.bin/git-duet:
        path: /usr/local/bin/git-duet-wrap-for-sops
        ignore-missing: true
    ~/.bin/git-duet-commit:
        path: /usr/local/bin/git-duet-wrap-for-sops
        ignore-missing: true
    ~/.bin/git-duet-install-hook:
        path: /usr/local/bin/git-duet-wrap-for-sops
        ignore-missing: true
    ~/.bin/git-duet-merge:
        path: /usr/local/bin/git-duet-wrap-for-sops
        ignore-missing: true
    ~/.bin/git-duet-post-commit:
        path: /usr/local/bin/git-duet-wrap-for-sops
        ignore-missing: true
    ~/.bin/git-duet-prepare-commit-msg:
       path: /usr/local/bin/git-duet-wrap-for-sops
       ignore-missing: true
    ~/.bin/git-duet-pre-commit:
        path: /usr/local/bin/git-duet-wrap-for-sops
        ignore-missing: true
    ~/.bin/git-duet-revert:
        path: /usr/local/bin/git-duet-wrap-for-sops
        ignore-missing: true
    ~/.bin/git-solo:
        path: /usr/local/bin/git-duet-wrap-for-sops
        ignore-missing: true

    # GnuPG
    ~/.gnupg/gpg-agent.conf: gnupg/gpg-agent.conf
    # Starship
    ~/.config/starship.toml: starship/starship.toml
    # Tmux
    ~/.config/tmux/tmux.conf: tmux/tmux.conf
    # Vim
    ~/.config/vim/.vimrc: vim/.vimrc
    # ZSH
    ~/.zshenv: zsh/.zshenv
    ~/.config/zsh/.zshrc: zsh/.zshrc
    # Kitty
    ~/.config/kitty/kitty.conf: kitty/kitty.conf
    ~/.config/kitty/dracula.conf: kitty/dracula.conf
    # Sops
    ~/.sops.yaml: sops/sops.yaml
    ~/.bin/1password: 1password/bin/1password
    # Cargo
    ~/.cargo/config: cargo/config

- create:
    - ~/Code/
    - ~/Downloads/
    - ~/Documents/
    - ~/Desktop/
    - ~/Library/Caches/
    - ~/Library/Caches/run/
    - ~/.local/share/
    # Tmux
    - ~/.config/tmux/plugins

- brewfile:
    - brew/Brewfile

- shell:
    - brew update
    - brew upgrade
    - brew cask upgrade
    - brew bundle cleanup --force --file="brew/Brewfile"
    - mas upgrade
    - rustup-init -y
    - rustup update
    - cargo install cargo-script
    - crontab - <"crontab/crontab"
    - ./fish/bin/make-default-shell
    - fish -c fisher
    - ./bash/bin/test
    - gcloud components update --quiet
    - ./git/bin/test
    - ./git-duet/bin/test
    - fix-gnupg-permissions
    - ./gnupg/bin/test
    - ./tldr/bin/test
    - ./vim/bin/test
    - fix-compaudit
    - ./zsh/bin/test
    - setup-a-keyring-for-sops secret-store purplebooth-secret-storage sops sops-key
    - bash -c "if [[ ! -f ~/.config/gcloud/application_sops_credentials.json ]] ; then cp \"~/.config/gcloud/application_default_credentials.json\" \"~/.config/gcloud/application_sops_credentials.json\" ; fi"
    - ./1password/bin/generate-envsecret
```
