### ISSUE TITLE
Dotbot bin script cannot find python

### ISSUE THREAD

**Issue by nkprince007** [anishathalye/dotbot#163] opened 2018-06-07 03:37 UTC
I get the following output when I run `./install`

```
error: cannot find python
/Volumes/Code/Developer/github/dotfiles/dotbot/bin/dotbot: line 14: return: can only `return' from a function or sourced script
/Volumes/Code/Developer/github/dotfiles/dotbot/bin/dotbot: line 44: unexpected EOF while looking for matching `''
/Volumes/Code/Developer/github/dotfiles/dotbot/bin/dotbot: line 46: syntax error: unexpected end of file
```

However, I have both python3 and python2 installed.

```bash
❯ which python3
/usr/local/bin/python3

❯ which python2
/usr/local/bin/python2

❯ which python
/usr/local/bin/python
```

**Comment by anishathalye** [comment] 2018-06-07 03:49
There is a bug in the install script. The `return 1` should be an `exit 1`, and that'll fix the rest of the error messages.

Though if you have Python installed, you shouldn't be seeing this in the first place. What system are you running on? What's your `sh` program?

**Comment by nkprince007** [comment] 2018-06-07 06:51
```bash
❯ uname -a
Darwin hogwarts.local 18.0.0 Darwin Kernel Version 18.0.0: Fri May 25 16:54:22 PDT 2018; root:xnu-4903.200.199.11.1~1/RELEASE_X86_64 x86_64

❯ which sh
/bin/sh

❯ sh --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by anishathalye** [comment] 2018-06-07 17:04
Huh, I have no idea why `which python` in the script doesn't return 0. Are you using different $PATHs when running the script vs using your terminal?

**Comment by micarlise** [comment] 2018-06-08 01:09
the dotbot install script is invoked using `/usr/bin/env sh`.  Because bash is being invoked as `sh` it starts up in backwards compatible mode; therefore won't source the usual system-wide startup files (and the `env` program strips out any of your exported variables).  My guess is that `/usr/local/bin` is not in your `$PATH` var in the sh startup.  

A quick test would be to run:

```
/usr/bin/env sh
echo $PATH
```

and check if `/usr/local/bin` is echoed to the terminal.

A more thorough examination would be to look at the contents of `/etc/profile` and `~/.profile` as those are the two startup files in `sh` mode that get sourced by bash (in that order).  On most gnu linux systems /etc/profile sources the contents of the files in `/etc/profile.d/*`.  However, os x is a bit different.  And it looks like you use zsh - so I'm also guessing that you don't have a `~/.profile` file.

**Comment by nkprince007** [comment] 2018-06-08 07:58
```
❯ /usr/bin/env sh
sh-3.2$ echo $PATH | grep /usr/local/bin
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/nkprince007/scripts:/Users/nkprince007/.config/yarn/global/node_modules/.bin:/usr/local/sbin:/usr/local/opt/go/libexec/bin:/Volumes/Code/Developer/gocode/bin:/Users/nkprince007/.antigen/bundles/robbyrussell/oh-my-zsh/lib:/Users/nkprince007/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/common-aliases:/Users/nkprince007/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/history:/Users/nkprince007/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git:/Users/nkprince007/.antigen/bundles/lukechilds/zsh-nvm:/Users/nkprince007/.antigen/bundles/marzocchi/zsh-notify:/Users/nkprince007/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/z:/Users/nkprince007/.antigen/bundles/zsh-users/zsh-autosuggestions:/Users/nkprince007/.antigen/bundles/zsh-users/zsh-syntax-highlighting
```
Clearly, `/usr/local/bin` is echoed, @micarlise.

**Comment by anishathalye** [comment] 2018-06-25 12:58
Hm, this is quite hard to debug without additional information. I think nobody else has been able to reproduce this bug.

I'm going to close this issue for now. Let us know if you have any additional information or a way we might be able to reproduce your bug, and if so, please reopen this issue.

**Closed by anishathalye** 2018-06-25 12:58 UTC
Labels: bug
