### ISSUE TITLE
Globbing with single file in source directory fails

### ISSUE THREAD

**Issue by DivineDominion** [anishathalye/dotbot#315] opened 2022-05-27 20:37 UTC
Running [d2f76a2](https://github.com/anishathalye/dotbot/commit/d2f76a25933f97cd37ef94e3bf9c134b9c55a02a), I found that this from the examples:

```yaml
link:
    ~/.config/:
        glob: true
        path: config/*
```

... does not work when you only have one file in the config directory.

Example:

    $ cd ~/.dotfiles
    $ mkdir config
    $ touch config/test.ini
    $ ./install
    ...
    Ambiguous action requested.
    No wildcard in glob, directory use undefined: ~/.config/ -> ['config/test.ini']
    Did you want to link the directory or into it?
    ...

As soon as you add another file, globbing works.

**Comment by niraami** [comment] 2022-07-05 20:01
Duplicate of #282, but yes, it's absolutely time to fix this @anishathalye ... I've expressed my opinion in the other issue.
As a side note, this [issue](https://github.com/anishathalye/dotbot/issues/284) (#284) and is very similar. People just expect glob to well.. be flexible.

**Comment by anishathalye** [comment] 2023-07-09 20:26
Thanks for bumping this. Dupe of #282, now fixed.

**Closed by anishathalye** 2023-07-09 20:26 UTC
